learn_templates/basicApp/urls.py
from django.conf.urls import url
from basicApp import views #from . import views

#template tagging
app_name = 'basicApp'

urlpatterns = [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
]

learn_templates/learn_templates/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basicApp import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'basicApp/',include('basicApp.urls'))
]

learn_templates/basicApp/models.py
from django.db import models

# Create your models here.

learn_templates/basicApp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basicApp/index.html',context_dict)

def other(request):
    return render(request,'basicApp/other.html')

def relative(request):
    return render(request,'basicApp/relative_url_templates.html')

learn_templates/templates/basicApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class= "navbar navbar-default nvabar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}">BRAND</a> </li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
          <li> <a class="navbar-link" href="{% url 'basicApp:other' %}">Other</a> </li>
        </ul>
      </div>
    </nav>
    <div class="cotainer">
      {% block body_block %}
      <!--  -->
      {% endblock %}
    </div>
  </body>
</html>

learn_templates/templates/basicApp/index.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
{% load my_extras %}
  {% block body_block %}
    <h1>WELCOME TO INDEX</h1>
    <h3>This is index.html page showing!!</h3>
    <!--  the | is to apply a python method, so upper is being used
          on text-->
    <h1> {{ text|mycut:'hello' }} </h1>
    <!--  the | is to apply a python method,
     25 is being added to 100-->
    <h4> {{ number|add:"25" }} </h4>
    {% endblock %}

learn_templates/templates/basicApp/other.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>This is an example of template inheritance</h2>
  {% endblock %}

learn_templates/templates/basicApp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basicApp:other' %}">the other page</a>
    <a href="{% url 'admin:index' %}">Link to admin</a>
    <a href="{% url 'index' %}">Index</a>
  </body>
</html>